name: test and front deploy

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [fst-chat, fst-chat-back]

    steps:
        # Désactiver Husky en CI
      - name: Disable Husky
        run: echo "HUSKY=0" >> $GITHUB_ENV
      # 1. Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v5

      # 2. Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      # 3. Installer les dépendances du projet correspondant
      - name: Install dependencies
        working-directory: ${{ matrix.project }}
        run: npm install

      # 4. Exécuter les tests
      - name: Run tests
        working-directory: ${{ matrix.project }}
        run: npm test
  
  changesCheck:
      runs-on: ubuntu-latest
      needs: test
      if: github.ref == 'refs/heads/main'
      outputs:
        back: ${{ steps.filter.outputs.back }}
        front: ${{ steps.filter.outputs.front }}
      steps:
        - uses: actions/checkout@v4
          with:
           fetch-depth: 0
        - name: Check for changes in fst-chat-back folder
          uses: dorny/paths-filter@v3
          id: filter
          with:
            filters: |
              back:
                - 'fst-chat-back/**'
              front:
                - 'fst-chat/**'

  pushFrontToprod:
      runs-on: ubuntu-latest
      needs: [changesCheck]
      if: ${{ needs.changesCheck.outputs.front == 'true'}}
      steps:
        
        - name: Checkout repository
          uses: actions/checkout@v5
          # Nécessaire pour garder le workflow du repo de déploiement
        - name: Prepare deploy folder with specific workflow
          run: |
            ls
            mkdir -p fst-chat/.github/workflows/
            cp .github/workflows/deploy.yml fst-chat/.github/workflows/
        - name: pushFrontToDeployRepo
          uses: cpina/github-action-push-to-another-repository@v1.7.2
          env: 
            API_TOKEN_GITHUB: ${{secrets.AUTH_TOKEN}}
          with:
           source-directory: fst-chat/
           destination-github-username: nokzs
           destination-repository-name: fst-tchat-front
           user-email: alexischapusot@gmail.com
           target-branch: main
 
  pushBackToprod:
      runs-on: ubuntu-latest
      needs: [changesCheck]
      if: ${{ needs.changesCheck.outputs.back == 'true'}} 
      steps:
        - name: Checkout repository
          uses: actions/checkout@v5
        
        - name: pushBackToDeployRepo
          uses: cpina/github-action-push-to-another-repository@v1.7.2
          env:
           API_TOKEN_GITHUB: ${{secrets.BACK_DEPLOY_TOKEN}}
          with:
           source-directory: fst-chat-back/
           destination-github-username: nokzs
           destination-repository-name: fst-tchat-back
           user-email: alexischapusot@gmail.com
           target-branch: main
            
